### PR TITLE
Fix all possible URL constant & false positive Theme Check issues 

### PR DESCRIPTION
**Pull request by agusmu**
Better to use trailingslashit() to make it consistent everywhere. It solves URL constant issues for once on forever.

Also, need to rename the functions to prevent "false positive" Theme Check and ThemeForest issues. The issue is not on Vafpress, but let's make Vafpress looks perfect. Agree?

### CODE REVIEW

**Comment by agusmu** [comment]
it is also solve #20 issue. no need to see this kind of issue in the future anymore

**Comment by agusmu** [comment]
Sorry, I accidentally add another commit here... The latest commit solve #21 issue

**Comment by agusmu** [comment]
One more, the latest commit also solves #15 issue

**Comment by agusmu** [comment]
Hmmm, why my latest commits are automatically added here... need to learn Github more...

**Comment by agusmu** [comment]
No problem, @ayublin and @daviedR please review these commits. let me know if you have any question.

**Comment by ayublin** [comment]
Thanks @agusmu :)

**Pull request merged**
